
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: component - PROPS_ALIASED_LOCALLY
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'Module': {
      'type': 'Component',
      'components': {
        'Module': {
          'extendsProps': [
            {
              'type': 'ReactNativeBuiltInType',
              'knownTypeName': 'ReactNativeCoreViewProps'
            }
          ],
          'events': [],
          'props': [
            {
              'name': 'otherStringProp',
              'optional': false,
              'typeAnnotation': {
                'type': 'StringTypeAnnotation',
                'default': null
              }
            },
            {
              'name': 'isEnabled',
              'optional': false,
              'typeAnnotation': {
                'type': 'BooleanTypeAnnotation',
                'default': false
              }
            },
            {
              'name': 'label',
              'optional': false,
              'typeAnnotation': {
                'type': 'StringTypeAnnotation',
                'default': null
              }
            },
            {
              'name': 'localType',
              'optional': false,
              'typeAnnotation': {
                'type': 'ObjectTypeAnnotation',
                'properties': [
                  {
                    'name': 'otherStringProp',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'StringTypeAnnotation',
                      'default': null
                    }
                  },
                  {
                    'name': 'isEnabled',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'BooleanTypeAnnotation',
                      'default': false
                    }
                  },
                  {
                    'name': 'label',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'StringTypeAnnotation',
                      'default': null
                    }
                  }
                ]
              }
            },
            {
              'name': 'localArr',
              'optional': false,
              'typeAnnotation': {
                'type': 'ArrayTypeAnnotation',
                'elementType': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': [
                    {
                      'name': 'otherStringProp',
                      'optional': false,
                      'typeAnnotation': {
                        'type': 'StringTypeAnnotation',
                        'default': null
                      }
                    },
                    {
                      'name': 'isEnabled',
                      'optional': false,
                      'typeAnnotation': {
                        'type': 'BooleanTypeAnnotation',
                        'default': false
                      }
                    },
                    {
                      'name': 'label',
                      'optional': false,
                      'typeAnnotation': {
                        'type': 'StringTypeAnnotation',
                        'default': null
                      }
                    }
                  ]
                }
              }
            }
          ],
          'commands': []
        }
      }
    }
  }
};
export default snapshot;
