
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: component - ONE_OF_EACH_PROP_EVENT_DEFAULT_AND_OPTIONS_NO_CAST
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'Module': {
      'type': 'Component',
      'components': {
        'Module': {
          'interfaceOnly': true,
          'excludedPlatforms': [
            'android'
          ],
          'paperComponentName': 'RCTModule',
          'extendsProps': [
            {
              'type': 'ReactNativeBuiltInType',
              'knownTypeName': 'ReactNativeCoreViewProps'
            }
          ],
          'events': [
            {
              'name': 'onDirectEventDefinedInlineNull',
              'optional': false,
              'bubblingType': 'direct',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onBubblingEventDefinedInlineNull',
              'optional': false,
              'bubblingType': 'bubble',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            }
          ],
          'props': [
            {
              'name': 'boolean_default_true_optional_both',
              'optional': true,
              'typeAnnotation': {
                'type': 'BooleanTypeAnnotation',
                'default': true
              }
            }
          ],
          'commands': []
        }
      }
    }
  }
};
export default snapshot;
