
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: component - PROPS_AS_EXTERNAL_TYPES
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'Module': {
      'type': 'Component',
      'components': {
        'Module': {
          'extendsProps': [],
          'events': [],
          'props': [
            {
              'name': 'disable',
              'optional': false,
              'typeAnnotation': {
                'type': 'StringTypeAnnotation',
                'default': null
              }
            },
            {
              'name': 'array',
              'optional': false,
              'typeAnnotation': {
                'type': 'ArrayTypeAnnotation',
                'elementType': {
                  'type': 'StringTypeAnnotation'
                }
              }
            }
          ],
          'commands': []
        }
      }
    }
  }
};
export default snapshot;
