
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: component - NO_PROPS_EVENTS_ONLY_DEPRECATED_VIEW_CONFIG_NAME_OPTION
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'Module': {
      'type': 'Component',
      'components': {
        'Module': {
          'deprecatedViewConfigName': 'DeprecateModuleName',
          'extendsProps': [
            {
              'type': 'ReactNativeBuiltInType',
              'knownTypeName': 'ReactNativeCoreViewProps'
            }
          ],
          'events': [],
          'props': [],
          'commands': []
        }
      }
    }
  }
};
export default snapshot;
