
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: component - EVENTS_DEFINED_AS_NULL_INLINE
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'Module': {
      'type': 'Component',
      'components': {
        'Module': {
          'extendsProps': [
            {
              'type': 'ReactNativeBuiltInType',
              'knownTypeName': 'ReactNativeCoreViewProps'
            }
          ],
          'events': [
            {
              'name': 'onDirectEventDefinedInlineNull',
              'optional': false,
              'bubblingType': 'direct',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onDirectEventDefinedInlineNullOptionalKey',
              'optional': true,
              'bubblingType': 'direct',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onDirectEventDefinedInlineNullOptionalValue',
              'optional': true,
              'bubblingType': 'direct',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onDirectEventDefinedInlineNullOptionalBoth',
              'optional': true,
              'bubblingType': 'direct',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onDirectEventDefinedInlineNullWithPaperName',
              'optional': true,
              'bubblingType': 'direct',
              'paperTopLevelNameDeprecated': 'paperDirectEventDefinedInlineNullWithPaperName',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onBubblingEventDefinedInlineNull',
              'optional': false,
              'bubblingType': 'bubble',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onBubblingEventDefinedInlineNullOptionalKey',
              'optional': true,
              'bubblingType': 'bubble',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onBubblingEventDefinedInlineNullOptionalValue',
              'optional': true,
              'bubblingType': 'bubble',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onBubblingEventDefinedInlineNullOptionalBoth',
              'optional': true,
              'bubblingType': 'bubble',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            },
            {
              'name': 'onBubblingEventDefinedInlineNullWithPaperName',
              'optional': true,
              'bubblingType': 'bubble',
              'paperTopLevelNameDeprecated': 'paperBubblingEventDefinedInlineNullWithPaperName',
              'typeAnnotation': {
                'type': 'EventTypeAnnotation',
                'argument': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': []
                }
              }
            }
          ],
          'props': [],
          'commands': []
        }
      }
    }
  }
};
export default snapshot;
