
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: module - NATIVE_MODULE_WITH_OBJECT_WITH_OBJECT_DEFINED_IN_FILE_AS_PROPERTY
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'NativeSampleTurboModule': {
      'type': 'NativeModule',
      'aliasMap': {
        'DisplayMetricsAndroid': {
          'type': 'ObjectTypeAnnotation',
          'properties': [
            {
              'name': 'width',
              'optional': false,
              'typeAnnotation': {
                'type': 'NumberTypeAnnotation'
              }
            }
          ]
        }
      },
      'enumMap': {},
      'spec': {
        'eventEmitters': [],
        'methods': [
          {
            'name': 'getConstants',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'ObjectTypeAnnotation',
                'properties': [
                  {
                    'name': 'Dimensions',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'ObjectTypeAnnotation',
                      'properties': [
                        {
                          'name': 'windowPhysicalPixels',
                          'optional': false,
                          'typeAnnotation': {
                            'type': 'TypeAliasTypeAnnotation',
                            'name': 'DisplayMetricsAndroid'
                          }
                        }
                      ]
                    }
                  }
                ]
              },
              'params': []
            }
          },
          {
            'name': 'getConstants2',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'ObjectTypeAnnotation',
                'properties': [
                  {
                    'name': 'Dimensions',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'ObjectTypeAnnotation',
                      'properties': [
                        {
                          'name': 'windowPhysicalPixels',
                          'optional': false,
                          'typeAnnotation': {
                            'type': 'TypeAliasTypeAnnotation',
                            'name': 'DisplayMetricsAndroid'
                          }
                        }
                      ]
                    }
                  }
                ]
              },
              'params': []
            }
          }
        ]
      },
      'moduleName': 'SampleTurboModule'
    }
  }
};
export default snapshot;
