
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: module - NATIVE_MODULE_WITH_PROMISE
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'NativeSampleTurboModule': {
      'type': 'NativeModule',
      'aliasMap': {
        'SomeObj': {
          'type': 'ObjectTypeAnnotation',
          'properties': [
            {
              'name': 'a',
              'optional': false,
              'typeAnnotation': {
                'type': 'StringTypeAnnotation'
              }
            }
          ]
        }
      },
      'enumMap': {},
      'spec': {
        'eventEmitters': [],
        'methods': [
          {
            'name': 'getValueWithPromise',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'PromiseTypeAnnotation',
                'elementType': {
                  'type': 'StringTypeAnnotation'
                }
              },
              'params': []
            }
          },
          {
            'name': 'getValueWithPromiseDefinedSomewhereElse',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'PromiseTypeAnnotation',
                'elementType': {
                  'type': 'StringTypeAnnotation'
                }
              },
              'params': []
            }
          },
          {
            'name': 'getValueWithPromiseObjDefinedSomewhereElse',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'PromiseTypeAnnotation',
                'elementType': {
                  'type': 'TypeAliasTypeAnnotation',
                  'name': 'SomeObj'
                }
              },
              'params': []
            }
          }
        ]
      },
      'moduleName': 'SampleTurboModule'
    }
  }
};
export default snapshot;
