
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: module - NATIVE_MODULE_WITH_COMPLEX_OBJECTS
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'NativeSampleTurboModule': {
      'type': 'NativeModule',
      'aliasMap': {},
      'enumMap': {},
      'spec': {
        'eventEmitters': [],
        'methods': [
          {
            'name': 'getObject',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'ObjectTypeAnnotation',
                'properties': [
                  {
                    'name': 'const1',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'ObjectTypeAnnotation',
                      'properties': [
                        {
                          'name': 'const1',
                          'optional': false,
                          'typeAnnotation': {
                            'type': 'BooleanTypeAnnotation'
                          }
                        }
                      ]
                    }
                  }
                ]
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'ObjectTypeAnnotation',
                    'properties': [
                      {
                        'name': 'const1',
                        'optional': false,
                        'typeAnnotation': {
                          'type': 'ObjectTypeAnnotation',
                          'properties': [
                            {
                              'name': 'const1',
                              'optional': false,
                              'typeAnnotation': {
                                'type': 'BooleanTypeAnnotation'
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            'name': 'getReadOnlyObject',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'ObjectTypeAnnotation',
                'properties': [
                  {
                    'name': 'const1',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'ObjectTypeAnnotation',
                      'properties': [
                        {
                          'name': 'const1',
                          'optional': false,
                          'typeAnnotation': {
                            'type': 'BooleanTypeAnnotation'
                          }
                        }
                      ]
                    }
                  }
                ]
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'ObjectTypeAnnotation',
                    'properties': [
                      {
                        'name': 'const1',
                        'optional': false,
                        'typeAnnotation': {
                          'type': 'ObjectTypeAnnotation',
                          'properties': [
                            {
                              'name': 'const1',
                              'optional': false,
                              'typeAnnotation': {
                                'type': 'BooleanTypeAnnotation'
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            'name': 'getObject2',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'GenericObjectTypeAnnotation'
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'ObjectTypeAnnotation',
                    'properties': [
                      {
                        'name': 'a',
                        'optional': false,
                        'typeAnnotation': {
                          'type': 'StringTypeAnnotation'
                        }
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            'name': 'getObjectInArray',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'ArrayTypeAnnotation',
                'elementType': {
                  'type': 'ObjectTypeAnnotation',
                  'properties': [
                    {
                      'name': 'const1',
                      'optional': false,
                      'typeAnnotation': {
                        'type': 'ObjectTypeAnnotation',
                        'properties': [
                          {
                            'name': 'const1',
                            'optional': false,
                            'typeAnnotation': {
                              'type': 'BooleanTypeAnnotation'
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'ObjectTypeAnnotation',
                    'properties': [
                      {
                        'name': 'const1',
                        'optional': false,
                        'typeAnnotation': {
                          'type': 'ObjectTypeAnnotation',
                          'properties': [
                            {
                              'name': 'const1',
                              'optional': false,
                              'typeAnnotation': {
                                'type': 'BooleanTypeAnnotation'
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      },
      'moduleName': 'SampleTurboModule'
    }
  }
};
export default snapshot;
