
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: module - ANDROID_ONLY_NATIVE_MODULE
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'NativeSampleTurboModule': {
      'type': 'NativeModule',
      'aliasMap': {},
      'enumMap': {},
      'spec': {
        'eventEmitters': [],
        'methods': []
      },
      'moduleName': 'SampleTurboModuleAndroid',
      'excludedPlatforms': [
        'iOS'
      ]
    }
  }
};
export default snapshot;
