
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: module - NATIVE_MODULE_WITH_UNION_RETURN_TYPES
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'NativeSampleTurboModule': {
      'type': 'NativeModule',
      'aliasMap': {},
      'enumMap': {},
      'spec': {
        'eventEmitters': [],
        'methods': [
          {
            'name': 'getStringUnion',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'StringLiteralUnionTypeAnnotation',
                'types': [
                  {
                    'type': 'StringLiteralTypeAnnotation',
                    'value': 'light'
                  },
                  {
                    'type': 'StringLiteralTypeAnnotation',
                    'value': 'dark'
                  }
                ]
              },
              'params': []
            }
          },
          {
            'name': 'setStringUnion',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'VoidTypeAnnotation'
              },
              'params': [
                {
                  'name': 'strings',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'StringLiteralUnionTypeAnnotation',
                    'types': [
                      {
                        'type': 'StringLiteralTypeAnnotation',
                        'value': 'light'
                      },
                      {
                        'type': 'StringLiteralTypeAnnotation',
                        'value': 'dark'
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            'name': 'getNumberUnion',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'UnionTypeAnnotation',
                'memberType': 'NumberTypeAnnotation'
              },
              'params': []
            }
          },
          {
            'name': 'setNumberUnion',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'VoidTypeAnnotation'
              },
              'params': [
                {
                  'name': 'numbers',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'UnionTypeAnnotation',
                    'memberType': 'NumberTypeAnnotation'
                  }
                }
              ]
            }
          },
          {
            'name': 'getObjectUnion',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'UnionTypeAnnotation',
                'memberType': 'ObjectTypeAnnotation'
              },
              'params': []
            }
          },
          {
            'name': 'setObjectUnion',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'VoidTypeAnnotation'
              },
              'params': [
                {
                  'name': 'objects',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'UnionTypeAnnotation',
                    'memberType': 'ObjectTypeAnnotation'
                  }
                }
              ]
            }
          }
        ]
      },
      'moduleName': 'SampleTurboModule'
    }
  }
};
export default snapshot;
