
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: module - CXX_ONLY_NATIVE_MODULE
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'NativeSampleTurboModule': {
      'type': 'NativeModule',
      'aliasMap': {
        'BinaryTreeNode': {
          'type': 'ObjectTypeAnnotation',
          'properties': [
            {
              'name': 'left',
              'optional': true,
              'typeAnnotation': {
                'type': 'TypeAliasTypeAnnotation',
                'name': 'BinaryTreeNode'
              }
            },
            {
              'name': 'value',
              'optional': false,
              'typeAnnotation': {
                'type': 'NumberTypeAnnotation'
              }
            },
            {
              'name': 'right',
              'optional': true,
              'typeAnnotation': {
                'type': 'TypeAliasTypeAnnotation',
                'name': 'BinaryTreeNode'
              }
            }
          ]
        },
        'CustomDeviceEvent': {
          'type': 'ObjectTypeAnnotation',
          'properties': [
            {
              'name': 'type',
              'optional': false,
              'typeAnnotation': {
                'type': 'StringTypeAnnotation'
              }
            },
            {
              'name': 'level',
              'optional': false,
              'typeAnnotation': {
                'type': 'NumberTypeAnnotation'
              }
            },
            {
              'name': 'degree',
              'optional': true,
              'typeAnnotation': {
                'type': 'NumberTypeAnnotation'
              }
            }
          ]
        },
        'GraphNode': {
          'type': 'ObjectTypeAnnotation',
          'properties': [
            {
              'name': 'label',
              'optional': false,
              'typeAnnotation': {
                'type': 'StringTypeAnnotation'
              }
            },
            {
              'name': 'neighbors',
              'optional': true,
              'typeAnnotation': {
                'type': 'ArrayTypeAnnotation',
                'elementType': {
                  'type': 'TypeAliasTypeAnnotation',
                  'name': 'GraphNode'
                }
              }
            }
          ]
        }
      },
      'enumMap': {
        'Quality': {
          'name': 'Quality',
          'type': 'EnumDeclarationWithMembers',
          'memberType': 'StringTypeAnnotation',
          'members': [
            {
              'name': 'SD',
              'value': {
                'type': 'StringLiteralTypeAnnotation',
                'value': 'SD'
              }
            },
            {
              'name': 'HD',
              'value': {
                'type': 'StringLiteralTypeAnnotation',
                'value': 'HD'
              }
            }
          ]
        },
        'Resolution': {
          'name': 'Resolution',
          'type': 'EnumDeclarationWithMembers',
          'memberType': 'NumberTypeAnnotation',
          'members': [
            {
              'name': 'Corrupted',
              'value': {
                'type': 'NumberLiteralTypeAnnotation',
                'value': -1
              }
            },
            {
              'name': 'Low',
              'value': {
                'type': 'NumberLiteralTypeAnnotation',
                'value': 720
              }
            },
            {
              'name': 'High',
              'value': {
                'type': 'NumberLiteralTypeAnnotation',
                'value': 1080
              }
            }
          ]
        },
        'StringOptions': {
          'name': 'StringOptions',
          'type': 'EnumDeclarationWithMembers',
          'memberType': 'StringTypeAnnotation',
          'members': [
            {
              'name': 'One',
              'value': {
                'type': 'StringLiteralTypeAnnotation',
                'value': 'one'
              }
            },
            {
              'name': 'Two',
              'value': {
                'type': 'StringLiteralTypeAnnotation',
                'value': 'two'
              }
            },
            {
              'name': 'Three',
              'value': {
                'type': 'StringLiteralTypeAnnotation',
                'value': 'three'
              }
            }
          ]
        }
      },
      'spec': {
        'eventEmitters': [],
        'methods': [
          {
            'name': 'getCallback',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'FunctionTypeAnnotation',
                'returnTypeAnnotation': {
                  'type': 'VoidTypeAnnotation'
                },
                'params': []
              },
              'params': []
            }
          },
          {
            'name': 'getMixed',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'MixedTypeAnnotation'
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'MixedTypeAnnotation'
                  }
                }
              ]
            }
          },
          {
            'name': 'getEnums',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'name': 'Quality',
                'type': 'EnumDeclaration',
                'memberType': 'StringTypeAnnotation'
              },
              'params': [
                {
                  'name': 'quality',
                  'optional': false,
                  'typeAnnotation': {
                    'name': 'Quality',
                    'type': 'EnumDeclaration',
                    'memberType': 'StringTypeAnnotation'
                  }
                },
                {
                  'name': 'resolution',
                  'optional': true,
                  'typeAnnotation': {
                    'name': 'Resolution',
                    'type': 'EnumDeclaration',
                    'memberType': 'NumberTypeAnnotation'
                  }
                },
                {
                  'name': 'stringOptions',
                  'optional': false,
                  'typeAnnotation': {
                    'name': 'StringOptions',
                    'type': 'EnumDeclaration',
                    'memberType': 'StringTypeAnnotation'
                  }
                }
              ]
            }
          },
          {
            'name': 'getBinaryTreeNode',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'TypeAliasTypeAnnotation',
                'name': 'BinaryTreeNode'
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'TypeAliasTypeAnnotation',
                    'name': 'BinaryTreeNode'
                  }
                }
              ]
            }
          },
          {
            'name': 'getGraphNode',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'TypeAliasTypeAnnotation',
                'name': 'GraphNode'
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'TypeAliasTypeAnnotation',
                    'name': 'GraphNode'
                  }
                }
              ]
            }
          },
          {
            'name': 'getMap',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'GenericObjectTypeAnnotation',
                'dictionaryValueType': {
                  'type': 'NullableTypeAnnotation',
                  'typeAnnotation': {
                    'type': 'NumberTypeAnnotation'
                  }
                }
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'GenericObjectTypeAnnotation',
                    'dictionaryValueType': {
                      'type': 'NullableTypeAnnotation',
                      'typeAnnotation': {
                        'type': 'NumberTypeAnnotation'
                      }
                    }
                  }
                }
              ]
            }
          },
          {
            'name': 'getAnotherMap',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'GenericObjectTypeAnnotation',
                'dictionaryValueType': {
                  'type': 'StringTypeAnnotation'
                }
              },
              'params': [
                {
                  'name': 'arg',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'GenericObjectTypeAnnotation',
                    'dictionaryValueType': {
                      'type': 'StringTypeAnnotation'
                    }
                  }
                }
              ]
            }
          },
          {
            'name': 'getUnion',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'UnionTypeAnnotation',
                'memberType': 'ObjectTypeAnnotation'
              },
              'params': [
                {
                  'name': 'chooseInt',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'UnionTypeAnnotation',
                    'memberType': 'NumberTypeAnnotation'
                  }
                },
                {
                  'name': 'chooseFloat',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'UnionTypeAnnotation',
                    'memberType': 'NumberTypeAnnotation'
                  }
                },
                {
                  'name': 'chooseObject',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'UnionTypeAnnotation',
                    'memberType': 'ObjectTypeAnnotation'
                  }
                },
                {
                  'name': 'chooseString',
                  'optional': false,
                  'typeAnnotation': {
                    'type': 'StringLiteralUnionTypeAnnotation',
                    'types': [
                      {
                        'type': 'StringLiteralTypeAnnotation',
                        'value': 'One'
                      },
                      {
                        'type': 'StringLiteralTypeAnnotation',
                        'value': 'Two'
                      },
                      {
                        'type': 'StringLiteralTypeAnnotation',
                        'value': 'Three'
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      },
      'moduleName': 'SampleTurboModuleCxx',
      'excludedPlatforms': [
        'iOS',
        'android'
      ]
    }
  }
};
export default snapshot;
