
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * DO NOT MODIFY
 * Generated by src/build.js
 * From snapshot: module - NATIVE_MODULE_WITH_COMPLEX_OBJECTS_WITH_NULLABLE_KEY
 */

import type { SchemaType } from '@react-native/codegen/lib/CodegenSchema';
const snapshot : SchemaType = {
  'modules': {
    'NativeSampleTurboModule': {
      'type': 'NativeModule',
      'aliasMap': {},
      'enumMap': {},
      'spec': {
        'eventEmitters': [],
        'methods': [
          {
            'name': 'getConstants',
            'optional': false,
            'typeAnnotation': {
              'type': 'FunctionTypeAnnotation',
              'returnTypeAnnotation': {
                'type': 'ObjectTypeAnnotation',
                'properties': [
                  {
                    'name': 'isTesting',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'BooleanTypeAnnotation'
                    }
                  },
                  {
                    'name': 'reactNativeVersion',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'ObjectTypeAnnotation',
                      'properties': [
                        {
                          'name': 'major',
                          'optional': false,
                          'typeAnnotation': {
                            'type': 'NumberTypeAnnotation'
                          }
                        },
                        {
                          'name': 'minor',
                          'optional': false,
                          'typeAnnotation': {
                            'type': 'NumberTypeAnnotation'
                          }
                        },
                        {
                          'name': 'patch',
                          'optional': true,
                          'typeAnnotation': {
                            'type': 'NumberTypeAnnotation'
                          }
                        },
                        {
                          'name': 'prerelease',
                          'optional': false,
                          'typeAnnotation': {
                            'type': 'NullableTypeAnnotation',
                            'typeAnnotation': {
                              'type': 'NumberTypeAnnotation'
                            }
                          }
                        }
                      ]
                    }
                  },
                  {
                    'name': 'forceTouchAvailable',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'BooleanTypeAnnotation'
                    }
                  },
                  {
                    'name': 'osVersion',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'StringTypeAnnotation'
                    }
                  },
                  {
                    'name': 'systemName',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'StringTypeAnnotation'
                    }
                  },
                  {
                    'name': 'interfaceIdiom',
                    'optional': false,
                    'typeAnnotation': {
                      'type': 'StringTypeAnnotation'
                    }
                  }
                ]
              },
              'params': []
            }
          }
        ]
      },
      'moduleName': 'SampleTurboModule'
    }
  }
};
export default snapshot;
